### ISSUE TITLE
TypeError: dest.write is not a function

### ISSUE THREAD

**Issue by natezerk** [ajoslin/conventional-changelog#111]
Getting an error using the basic changelog task in Gulp.

```
gulp.task('changelog', function () {
    return gulp.src('CHANGELOG.md', {
        buffer: false
    })
      .pipe(conventionalChangelog({
          preset: 'angular'
      }))
      .pipe(gulp.dest('./'));
});
```

Running this task gives me an error at like 623 of _stream_readable.js, at var written = dest.write(chunk). 

TypeError: dest.write is not a function.

Not really sure what the problem is here?

**Comment by stevemao** [comment]
Are you using https://github.com/stevemao/gulp-conventional-changelog?

**Comment by stevemao** [comment]
Whats the whole stack?

**Comment by stevemao** [comment]
closing due to inactivity

**Comment by klarkc** [comment]
+1

I am having the same issue, here is the whole stack:

```
$ gulp changelog
[17:35:43] Using gulpfile ~/src/gulpfile.js
[17:35:43] Starting 'changelog'...
/home/klarkc/src/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623
    var written = dest.write(chunk);
                       ^
TypeError: undefined is not a function
    at write (/home/klarkc/src/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/home/klarkc/src/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/home/klarkc/src/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:104:17)
    at emitReadable_ (/home/klarkc/src/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/home/klarkc/src/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/home/klarkc/src/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (/home/klarkc/src/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
    at DestroyableTransform.Transform.push (/home/klarkc/src/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
    at afterTransform (/home/klarkc/src/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:101:12)
```

and the code in gulpfile.js:
```javascript
gulp.task('changelog', function () {
    var src = gulp.src('CHANGELOG.md', {
        buffer: false
    });
    return src
        .pipe(conventionalChangelog({
            preset: 'angular' // Or to any other commit message convention you use.
        }))
        .pipe(gulp.dest('./'));
});
```

**Comment by stevemao** [comment]
@klarkc Are you using https://github.com/stevemao/gulp-conventional-changelog?

**Comment by klarkc** [comment]
@stevemao I am using https://github.com/ajoslin/conventional-changelog it was installed through npm package manager, the version is 0.5.2.

**Comment by stevemao** [comment]
@klarkc You need to use the gulp wrapper.

**Comment by klarkc** [comment]
@stevemao Oh ok, I see. It's working now with gulp-conventional-changelog. It could be useful add a note to READEME.md with a link to the gulp wrapper or others wrappers, if it is not a problem.

**Comment by stevemao** [comment]
> Or use one of the plugins if you are already using the tool: grunt/gulp/atom
