### ISSUE TITLE
Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by sebastienbarre** [ajoslin/conventional-changelog#123]
(master)$ conventional-changelog -p angular -r 0
TypeError: Cannot read property 'version' of undefined

I should add that this is not a node/npm/Javascript repo, there is no package.json here. Nevertheless, I'd like to use Angular's commit log conventions for all my projects and generate a weekly changelog, say, for the work that was done in the past 7 days. Maybe by passing it a date, or a reference to a commit SHA1, so that it would generate a log based on all the changes since that date/commit.

Thanks

**Comment by stevemao** [comment]
v0.5.3

**Comment by vladikoff** [comment]
@stevemao still getting this error

➜  fxa-content-server git:(master) conventional-changelog -p angular -i CHANGELOG.md -w
TypeError: Error in conventional-changelog-writer: Cannot read property '0' of undefined
➜  fxa-content-server git:(master) conventional-changelog --version                    
0.5.3

**Comment by stevemao** [comment]
@vladikoff Can you provide the full stack?

**Comment by vladikoff** [comment]
@stevemao Oh that's all I get, str:

just clone : 

```
git clone git@github.com:mozilla/fxa-content-server.git
cd fxa-content-server 
conventional-changelog -p angular -i CHANGELOG.md -w
```

**Comment by vladikoff** [comment]
Ah I guess this is coming from somewhere else. No help with `--verbose`

**Comment by vladikoff** [comment]
With a bit of tracing through the files, it is erroring here: https://github.com/stevemao/conventional-changelog-writer/blob/master/index.js#L129

```
TypeError: Cannot read property '0' of undefined
    at Object.Q.allSettled.spread._.assign.finalizeContext (/Users/vladikoff/mozilla/fxa-local-dev/conventional-changelog/index.js:207:73)
    at Object.generate (/Users/vladikoff/mozilla/fxa-local-dev/conventional-changelog/node_modules/conventional-changelog-writer/lib/util.js:175:21)
    at DestroyableTransform.through.obj.keyCommit [as _transform] (/Users/vladikoff/mozilla/fxa-local-dev/conventional-changelog/node_modules/conventional-changelog-writer/index.js:109:25)
    at DestroyableTransform.Transform._read (/Users/vladikoff/mozilla/fxa-local-dev/conventional-changelog/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/Users/vladikoff/mozilla/fxa-local-dev/conventional-changelog/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/Users/vladikoff/mozilla/fxa-local-dev/conventional-changelog/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:335:12)
    at writeOrBuffer (/Users/vladikoff/mozilla/fxa-local-dev/conventional-changelog/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:321:5)
    at DestroyableTransform.Writable.write (/Users/vladikoff/mozilla/fxa-local-dev/conventional-changelog/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:248:11)
    at DestroyableTransform.ondata (/Users/vladikoff/mozilla/fxa-local-dev/conventional-changelog/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:583:20)
    at emitOne (events.js:77:13)
```
