### ISSUE TITLE
Error in conventional-commits-parser: no writecb in Transform class

### ISSUE THREAD

**Issue by vladikoff** [ajoslin/conventional-changelog#130]
```
Running "conventionalChangelog:release" (conventionalChangelog) task
fxa-content-server.CRITICAL: uncaughtException Error: Error in conventional-commits-parser: no writecb in Transform class
    at afterTransform (/Users/vladikoff/mozilla/fxa-local-dev/fxa-content-server/node_modules/grunt-conventional-changelog/node_modules/conventional-changelog/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:75:33)
    at TransformState.afterTransform (/Users/vladikoff/mozilla/fxa-local-dev/fxa-content-server/node_modules/grunt-conventional-changelog/node_modules/conventional-changelog/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:59:12)
    at DestroyableTransform._transform (/Users/vladikoff/mozilla/fxa-local-dev/fxa-content-server/node_modules/grunt-conventional-changelog/node_modules/conventional-changelog/node_modules/conventional-commits-parser/index.js:80:9)
    at DestroyableTransform.Transform._read (/Users/vladikoff/mozilla/fxa-local-dev/fxa-content-server/node_modules/grunt-conventional-changelog/node_modules/conventional-changelog/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/Users/vladikoff/mozilla/fxa-local-dev/fxa-content-server/node_modules/grunt-conventional-changelog/node_modules/conventional-changelog/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/Users/vladikoff/mozilla/fxa-local-dev/fxa-content-server/node_modules/grunt-conventional-changelog/node_modules/conventional-changelog/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:335:12)
    at writeOrBuffer (/Users/vladikoff/mozilla/fxa-local-dev/fxa-content-server/node_modules/grunt-conventional-changelog/node_modules/conventional-changelog/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:321:5)
    at DestroyableTransform.Writable.write (/Users/vladikoff/mozilla/fxa-local-dev/fxa-content-server/node_modules/grunt-conventional-changelog/node_modules/conventional-changelog/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:248:11)
    at Readable.ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
    at Readable.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Readable.push (_stream_readable.js:110:10)
    at DestroyableTransform._transform (/Users/vladikoff/mozilla/fxa-local-dev/fxa-content-server/node_modules/grunt-conventional-changelog/node_modules/conventional-changelog/node_modules/git-raw-commits/index.js:36:16)
    at DestroyableTransform.Transform._read (/Users/vladikoff/mozilla/fxa-local-dev/fxa-content-server/node_modules/grunt-conventional-changelog/node_modules/conventional-changelog/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/Users/vladikoff/mozilla/fxa-local-dev/fxa-content-server/node_modules/grunt-conventional-changelog/node_modules/conventional-changelog/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
Fatal error: Error in conventional-commits-parser: no writecb in Transform class
```

Using via `"grunt-conventional-changelog": "5.0.0",`

Task configuration:
```
module.exports = function (grunt) {
  grunt.config('conventionalChangelog', {
    options: {
      changelogOpts: {}
    },
    release: {
      src: 'CHANGELOG.md'
    }
  });
};
```

Any ideas?

**Comment by stevemao** [comment]
I think its the grunt wrapper that doesn't print out the real error message. I'll work on that.

**Comment by vladikoff** [comment]
Hm thanks, thought it was node 4 issue, but yeah something else is going on in my case

**Comment by stevemao** [comment]
note to myself: the error handling is always a problem although I'm trying to fix it a few times. There must be a better way.

**Comment by vladikoff** [comment]
Yeah this is strange, I think some sub-dependency regressed in the past 2 weeks. I was able to create this tag 2 weeks ago https://github.com/mozilla/fxa-content-server/commit/deaabfd5176460c9418f2aeba95dc0e9ccdacd2e but now it fails with that error 

in node 0.10 
- with conventional-changelog 3 the task hangs

in node 0.10 and node 4 with conventional-changelog 4 and 5 the task whose the whitecb error.

**Comment by stevemao** [comment]
There might be something in the commit messages. I was saying the tool should print what the error is instead of `no writecb in Transform class` :(

This happens to me many times before and hard for me to debug. And I thought I fixed it :(

Once there are error messages printed you should be able to find out what's wrong easily.

**Comment by vladikoff** [comment]
fixed in https://github.com/stevemao/git-semver-tags/issues/3

thanks again!

**Comment by stevemao** [comment]
I would like to keep this open to track meaningful error messages :)

**Comment by vladikoff** [comment]
:+1:
