### ISSUE TITLE
Uncaught, unspecified "error" event.

### ISSUE THREAD

**Issue by yoannmoinet** [ajoslin/conventional-changelog#64]
Hi, I'm having an uncaught error when using the CLI.

### Environment
- conventional-changelog@next
- Windows 7
- Node v0.12.5 & IOjs v2.3.2
- NPM v2.11.2 & v2.11.3

Is it Unix only maybe?

### Repro
It happens when running either : 

```bash
node ./node_modules/conventional-changelog/cli -i CHANGELOG.md -w -b
convetional-changelog -i CHANGELOG.md -w -b
```

with or without flags

### Stack
Here's the stack : 
```bash
events.js:87
      throw Error('Uncaught, unspecified "error" event.');
            ^
Error: Uncaught, unspecified "error" event.
    at Error (native)
    at Readable.emit (events.js:87:13)
    at Readable.<anonymous> (.\node_modules\conventional-changelog\index.js:144:20)
    at Readable.emit (events.js:107:17)
    at DestroyableTransform._transform (.\node_modules\conventional-changelog\node_modules\git-raw-commits\index.js:48:16)
    at DestroyableTransform.Transform._read (.\node_modules\conventional-changelog\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (.\node_modules\conventional-changelog\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:160:12)
    at doWrite (.\node_modules\conventional-changelog\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:323:12)
    at writeOrBuffer (.\node_modules\conventional-changelog\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:309:5)
    at DestroyableTransform.Writable.write (.\node_modules\conventional-changelog\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:236:11)

```

### When handling Readable's errors : 
I've tried handling the readable's errors with : 
```node
readable.on('error', function(err) {
    console.log(err);
});
```
It's removed the Uncaught Error and printed
```
Error in git-raw-commits. fatal: unrecognized argument: ------------------------'
```

I've also printed the options passed to `gitRawCommits` : 
```
{
    format: '%B%n-hash-%n%H%n-gitTags-%n%d%n-committerDate-%n%ci',
    from: 'v2.0.0'
}
```

### Git Log
Here's my git log if it can help : 

```
feat: try to trigger changelog
docs: update changelog generation
docs: update changelog
docs: clean generated changelog
docs: update changelog
v2.0.0
feat(npm): add scripts
feat: add changelog
fix: README
fix: README
feat: add Travis CI
feat: add linting
feat: add defaults template values
style: clarify function's name
style: use private variables, setters and getters
style: add new lines, semi-colons and move variables
chore: v1.6.0
fix: return object when the result is an object and not a9f931e2e10acf4108574cff365274d80819bbb3b chore: v1.5.0
feat: add `langs` to list all available languages
fix(has): check for the language before the key
chore: v1.4.0
test: add tests
fix: use default `lng` in `has` function
fix: return `key` if inexistant
fix: use default object if `data` isn't provided
chore: change `string` to `dico`
chore: v1.3.0
docs(get): update docs with new feature for overwrite
feat(get): add the possibility to overwrite language
chore: v1.2.0
docs: update docs with `has` and other small adjustements
feat: add `has` function to check on availability of loca
chore: add badges to readme
v1.1.0
fix: update commonjs and amd support
v1.0.1
chore: update readme
chore: format readme
docs: add documentation
feat: change `t` to `get`
chore: typo in readme
feat: npm support
feat: bower support
feat: add lib
Initial commit
```

Thanks for your awesome tool anyway.

**Comment by stevemao** [comment]
Hm... looks like the shell command doesn't work for windows. Are you familiar with git for windows (as you can see I don't have a windows machine)? If you are, can you patch it with the correct shell command? Thanks.

The shell template is here:
https://github.com/stevemao/git-raw-commits/blob/master/index.js#L22-L25

**Comment by stevemao** [comment]
Btw, the `readable` which you have `error` listener on is the returned stream of `conventionalChangelog()` right?

**Comment by yoannmoinet** [comment]
The git command should work on Windows the same way it does on Unix based machines. 
I'll look into that, it must be an escape or special character not working on Windows.

The `readable` I was listening on was the one from [`index.js:21`](https://github.com/ajoslin/conventional-changelog/blob/master/index.js#L21)

I'll try to patch that tomorrow.

**Comment by stevemao** [comment]
Thank you @yoannmoinet .

**Comment by stevemao** [comment]
@yoannmoinet I've published 0.1.0-alpha.2, can you reinstall and see if it works fine? Thanks for your time.

**Comment by stevemao** [comment]
I guess I'll add window ci for all my modules, but the config looks like pain in the arse. https://github.com/sindresorhus/appveyor-node/blob/master/appveyor.yml

**Comment by yoannmoinet** [comment]
Thanks @stevemao. Welcome to the '_web on windows_'. It **IS** a pain in the arse.
